/** @deprecated use VelocityVisuals — kept for backward compatibility */
export {
  SiteAtmosphere,
  LightTrailLayer,
  VelocityGraph,
  RisingNeonGraph,
  GrowthGridBackground,
  CountUp,
  ImpactStatsStrip,
  RapidDeliveryPanel,
  MiniGrowthSpark,
  GrowthInsightCards,
  AlgoDotGrid,
  AlgorithmNetwork,
  AiCyberBackdrop,
  BounceArrow,
  FloatingEngagementBadges,
  FloatingMetricBadges,
  RisingArrowsDecor,
} from "@/components/VelocityVisuals";
